= Problemverständnis

Die Therapieadhäsion, auch bekannt als Therapietreue, bezieht sich auf die Fähigkeit eines
Patienten, eine empfohlene Behandlung oder Therapie genau zu befolgen. Eine hohe Adhärenz ist entscheidend für eine erfolgreiche Behandlungen und Verbesserung der Gesundheit von Patienten:innen.
Laut der Weltgesundheitsorganisation (WHO) nehmen nur 47 Prozent der Menschen mit chronischen Erkrankungen ihre Medikamente wie verordnet ein. Verglesslichkeit, Angst vor Nebenwirkungen oder missverstandene Anweisungen sind häufige Gründe für eine niedrige Adhärenz. Nach Schätzungen zu Folge sterben jährlich 125.000 Menschen in den USA und 200.000 Menschen in Europa aufgrund nicht eingehaltener Therapiepläne. Neben der verschlechtertem oder stagnierendem Gesundheitzustand bei nicht Einhaltung eines Therapieplans wird angenommen, dass bis zu 21 % der Aufnahmen in Pflegeheime, 10 % der Krankenhausaufnahmen und viele Arztbesuche, diagnostische Tests und unnötige Behandlungen vermieden werden könnten #cite(<msdmanuals2025>) mit einer höheren Adhärenz. Diese Zahlen verdeutlichen die Notwendigkeit und Nutzen eines Medizinischen Informationssystems, das Patienten:innen bei der Einhaltung ihrer Therapiepläne unterstützt. Wir möchten als Informatiker aber auch als Patienten unsere Expertise aus der Mensch Maschine Interaktion ein solches System entwickeln, das Patienten:innen dabei hilft, ihre Therapien besser zu verstehen und einzuhalten. Das System soll primär Patienten:innen dabei unterstützen, ihre Therapien zu verstehen und einzuhalten. 

Chronische Krankheiten, körperliche und geistige Beeinträchtigungen oder auch hohen Mengen an Einzunehmenden Arzneimitteln sind entscheidende Faktoren, die alle dazu beitragen einen Therapieplan zu vernachlässigen. Vorallem diesen Patienten sollen Unterstützung geboten werden, um ihre Therapien besser zu verstehen und einzuhalten. 

= Zieldefinition
Unser Ziel ist es, ein Medizinisches Informationssystem zu entwickeln, das Patienten:innen Informationen über die Therapie bereitstellt, Erinnerungen an die Einnahme von Medikamenten entsendet und Einsicht in die Arzneimitteln, den Therapieplan und den Fortschritt ermöglicht. Das System soll einfach zu bedienen sein und durch ein intuitives Design eine breite Nutzerbasis zu erreichen. 
Unser Hauptziel ist es, die Adhärenz der Patienten zu erhöhen und somit die Gesundheit und Lebensqualität der Patienten zu verbessern. Über eine mobile Anwendung und eine benutzerfreundliche Oberfläche soll das System Patienten aller Altersgruppen und mit unterschiedlichen technischen Fähigkeiten ansprechen. Das System soll auch die Möglichkeit bieten, den Fortschritt der Therapie zu verfolgen und Feedback zu geben, um die Motivation der Patienten zu steigern. Patienten halten eine Behandlung besser ein, wenn sie eine gute Beziehung zu ihrem Arzt und/oder Apotheker haben und besser ihren Therapieplan und Medikamente verstehen. 